# Generated by Django 4.1.6 on 2023-02-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("climateApp", "0002_datasource_registered_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasource",
            name="name",
            field=models.CharField(max_length=80, verbose_name="Data Source Name"),
        ),
    ]
