# Generated by Django 4.1.6 on 2023-02-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("climateApp", "0003_alter_datasource_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="Resource Name")),
                (
                    "material",
                    models.CharField(max_length=80, verbose_name="Material Type"),
                ),
                ("cotwovalue_aonethree", models.IntegerField()),
                ("cotwovalue_conefour", models.IntegerField()),
                (
                    "prod_country",
                    models.CharField(
                        max_length=80, verbose_name="Country of production"
                    ),
                ),
                ("certifier", models.ManyToManyField(to="climateApp.datasource")),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
