# Generated by Django 4.1.6 on 2023-02-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("climateApp", "0004_resource"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="producer",
            field=models.CharField(
                max_length=80, null=True, verbose_name="Company Name"
            ),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="registered_country",
            field=models.CharField(
                max_length=80, null=True, verbose_name="Country of registration"
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="cotwovalue_aonethree",
            field=models.FloatField(verbose_name="A1-A3 - Materials (kg CO2e)"),
        ),
        migrations.AlterField(
            model_name="resource",
            name="cotwovalue_conefour",
            field=models.FloatField(verbose_name="C1-C4 - End of life (kg CO2e)"),
        ),
    ]
