# Generated by Django 4.1.6 on 2023-02-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("climateApp", "0005_resource_producer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="material",
            field=models.CharField(
                choices=[
                    (
                        "Structural steel and steel profiles",
                        "Structural steel and steel profiles",
                    ),
                    (
                        "Reinforcement for concrete (rebar)",
                        "Reinforcement for concrete (rebar)",
                    ),
                    ("Fresh concrete", "Fresh concrete"),
                ],
                max_length=120,
                verbose_name="Material Type",
            ),
        ),
    ]
